<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Po.Navigation.Core</PackageId>
		<Version>0.0.1</Version>
		<Description>Navigation infrastructure for .NET applications.</Description>
		<PackageTags>Navigation;MVVM;Core</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Po.MVVM.Core\Po.MVVM.Core.csproj" />
  </ItemGroup>

</Project>
