<Project>

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<Authors>Po</Authors>
		<Company>Po</Company>
		<RepositoryUrl></RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<IncludeSymbols>false</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildProjectDirectory)\README.md"
              Pack="true"
              PackagePath="/" />
	</ItemGroup>

</Project>