<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Po.Navigation.Avalonia</PackageId>
		<Version>0.0.1</Version>
		<Description>Region-based navigation framework for Avalonia applications.</Description>
		<PackageTags>Avalonia;Navigation;MVVM;Region</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Po.Navigation.Core\Po.Navigation.Core.csproj" />
  </ItemGroup>

</Project>
