<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Po.MVVM.Core</PackageId>
		<Version>0.0.1</Version>
		<Description>Lightweight MVVM infrastructure for .NET applications.</Description>
		<PackageTags>MVVM;CommunityToolkit;ObservableObject;ViewModel</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
	</ItemGroup>

</Project>
