name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore
      - name: Pack
        run: dotnet pack -c Release -o packages

      # 使用 GitHub OIDC 登录 NuGet
      - name: NuGet login (OIDC)
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: Underdog

      # 推送 NuGet 包
      - name: Push NuGet packages
        run: |
          dotnet nuget push "packages/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
            --skip-duplicate
